version: 2

jobs:
  deploy:
    docker:
      - image: cimg/python:3.12.3
    working_directory: ~/myGPTReader
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: deploy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli jinja2
            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
            source $BASH_ENV
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            sh deploy/docker_build.sh
            sh deploy/docker_push.sh
            sh deploy/deploy.sh

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches: { only: [main] }
